spring:
  data:
    mongodb:
      uri: mongodb://localhost:27077/local

application:
  security:
    jwt:
      algorithm: HS256
      accessSecretKey: "accessSecretKey"
      accessTokenExpirationMinutes: 10
      refreshTokenExpirationHours: 2

  rest:
    connectionTimeout: 5000
    readTimeout: 15000
    maxInMemorySizeBytes: 31457280

  external:
    yandex:
      enabled: false
      oAuthToken: "***"
      folderId: "***"
      tokenUrl: "https://iam.api.cloud.yandex.net/iam/v1/tokens"
      translateApiUrl: "https://translate.api.cloud.yandex.net/translate"
    deepl:
      enabled: false
      authKey: "***"
    joke-api:
      baseUrl: "https://official-joke-api.appspot.com/jokes"
